### ISSUE TITLE
Incorrect Docs

### ISSUE THREAD

**Issue by benyanke** [gongonpower/glusterfs-swarm#1]
https://github.com/gongonpower/glusterfs-swarm#tips--why-not-use-docker-compose-yml-format

```
When using yml format to run a container, the container name will be the format "xxx_yyy". The name has an undersore inside. glusterfs treats this name as invalid and refuse to perform any action e.g.(gluster peer probe gfsc1). The only way is used docker run to create a container with the name we wanted.
```

This is actually not true - you can specify with `container_name`.

https://docs.docker.com/compose/compose-file/

**Comment by gongonpower** [comment]
Thank you for your helpful information. The yml format tips paragraph was removed. 

commit bd7286bd21c9df108fae310eed9bc7f4019cf8ed

**Comment by gongonpower** [comment]
After more consideration, the information of the tips paragraph is worth keeping. So the paragraph is added again with updated content.

commit e9d687af560a46d0814be0cc271a77c87d783160
